version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - ENV=development
      - MONGODB_URI=mongodb://mongodb:27017
    networks:
      - backend-network
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network:
